# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd6026382bb6e455cacae758273077f8f483d28b5a3981674508eabd9283ce2977eb47b1116b7bc5084830052495ae5c2fc8ae685a3ace461f0b5a2860d4e988

test:
  secret_key_base: a698fc5f679c5a947c651023860011c8ffe1e94e35788f46ffe27ad13f7dca972358b0c119adb5a08440ff4b8e181e66ca0d10b863c64a74eee7047fa7497244

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
